import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { Browser, BrowserContext, Page } from "@playwright/test";
import { sid } from "../../../scripts/lib/ids";
import { sql } from "../../db/harness";
import { authState } from "../support/auth";
import { expect, test } from "../support/fixtures";

// §6 — the Alex demo, start to finish, on the demo seed. Each step saves a screenshot to docs/demo/screenshots
// and the run writes docs/demo/WALKTHROUGH.md. Steps that need a key this environment doesn't have (Stripe
// card payments) show the app's honest "not configured" state and are recorded as HANDOFF — never as PASS.
const R = sid("tenant:ridgeline");
const MAYA = sid("person:ridgeline:maya-cooper");
const ROOT = path.resolve(import.meta.dirname, "../../..");
const SHOTS = path.join(ROOT, "docs/demo/screenshots");
const stripeReady = Boolean(process.env.STRIPE_SECRET_KEY);
type Status = "PASS" | "HANDOFF" | "SKIP";
const log: { n: string; title: string; status: Status; note: string; file: string }[] = [];

async function shot(page: Page, n: string, slug: string, title: string, status: Status = "PASS", note = ""): Promise<void> {
  const file = `${n}-${slug}.png`;
  await page.screenshot({ path: path.join(SHOTS, file) });
  log.push({ n, title, status, note, file });
}

test.beforeAll(() => { mkdirSync(SHOTS, { recursive: true }); });

test.afterAll(() => {
  const lines = [
    "# The Alex demo — walkthrough",
    "",
    "Generated by `tests/e2e/demo/alex-walkthrough.spec.ts` (§6 of the spec) on the demo seed. Each screenshot is taken",
    "by the test at that step. AI results come from recorded dev fixtures (no OpenRouter key in the build environment)",
    "and are labelled \"dev fixture\" in the app. **HANDOFF** marks a step whose live part needs a key this run didn't",
    "have — see [docs/HANDOFF.md](../HANDOFF.md).",
    "",
    `Run: ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC · Stripe ${stripeReady ? "configured" : "not configured"}`,
    "",
  ];
  for (const s of log) lines.push(`## ${s.n}. ${s.title} — ${s.status}`, "", ...(s.note ? [s.note, ""] : []), `![${s.title}](screenshots/${s.file})`, "");
  writeFileSync(path.join(ROOT, "docs/demo/WALKTHROUGH.md"), `${lines.join("\n")}\n`);
});

const ctxFor = (browser: Browser, who: "owner" | "instructor" | "parent" | null, size: { width: number; height: number }): Promise<BrowserContext> =>
  browser.newContext({ ...(who ? { storageState: authState("ridgeline", who) } : {}), viewport: size });

test.describe("@demo Alex walkthrough (§6)", () => {
  test.describe.configure({ mode: "serial" });
  test.use({ actionTimeout: 15_000 });

  test("all fifteen steps and the close, on the demo seed", async ({ browser, request }) => {
    test.setTimeout(15 * 60_000);
    const desk = await (await ctxFor(browser, "owner", { width: 1440, height: 900 })).newPage();
    const mat = await (await ctxFor(browser, "instructor", { width: 1024, height: 768 })).newPage();
    const home = await (await ctxFor(browser, "parent", { width: 390, height: 844 })).newPage();
    const job = async (name: string) => {
      const r = await request.post(`/api/jobs/${name}?tenant=${R}`, { headers: { authorization: `Bearer ${process.env.CRON_SECRET}` } });
      expect(r.ok(), await r.text()).toBe(true);
    };

    // ---------------------------------------------------------------- Part 1: parity
    await test.step("1. Desk dashboard with live counts", async () => {
      await desk.goto("/desk");
      for (const label of ["Active students", "Attendance this week", "At risk", "Trials", "MRR", "Past due", "Next test", "Low stock"]) {
        await expect(desk.getByRole("link", { name: new RegExp(`^${label}`) }).first()).toBeVisible();
      }
      const [{ n: active } = { n: 0 }] = await sql<{ n: number }[]>`select count(*)::int as n from people where tenant_id = ${R} and status = 'active' and 'student' = any (type_flags) and archived_at is null`;
      await expect(desk.getByRole("link", { name: /^Active students/ })).toContainText(String(active));
      await shot(desk, "01", "dashboard", "Desk dashboard: live counts");
    });

    await test.step("2. People → Cooper household → profile", async () => {
      await desk.goto("/desk/people");
      await desk.getByRole("searchbox", { name: "Search people" }).fill("Cooper");
      await desk.getByRole("link", { name: "Cooper family" }).first().click();
      await desk.waitForURL(/\/desk\/households\//);
      const members = desk.getByRole("region", { name: "Members" });
      await expect(members).toContainText("Maya Cooper");
      await expect(members).toContainText("Leo Cooper");
      await shot(desk, "02", "household", "People → search \"Cooper\" → the household with two kids");
      await members.getByRole("link", { name: "Maya Cooper" }).first().click();
      await expect(desk.getByRole("heading", { level: 1, name: "Maya Cooper" })).toBeVisible();
      await shot(desk, "02b", "profile", "Maya's profile: rank and requirements, attendance, billing, documents, messages");
    });

    const [tonight] = await sql<{ id: string; week: string }[]>`
      select s.id, (date_trunc('week', s.starts_at at time zone 'America/New_York'))::date::text as week from class_sessions s
      where s.tenant_id = ${R} and exists (select 1 from bookings b where b.session_id = s.id and b.status = 'waitlisted') and s.starts_at > now() - interval '3 hours'
      order by s.starts_at limit 1`;
    await test.step("3. Schedule → tonight's Youth TKD session → roster with booked/waitlisted", async () => {
      await desk.goto(`/desk/schedule?week=${tonight?.week}`);
      await desk.locator(`a[href="/desk/schedule/sessions/${tonight?.id}"]`).first().click();
      await expect(desk.getByText(/waitlist/i).first()).toBeVisible();
      await expect(desk.getByText(/booked/i).first()).toBeVisible();
      await shot(desk, "03", "session", "Schedule → tonight's Youth Taekwondo session: booked and waitlisted");
    });

    await test.step("4. Mat (tablet): 5 check-ins, a stripe, a skill sign-off", async () => {
      await mat.goto(`/mat/session/${tonight?.id}`);
      const roster = mat.getByRole("list", { name: "Roster" });
      await roster.getByRole("button", { name: /^Leo Cooper, not checked in/ }).click();
      for (let i = 0; i < 4; i++) {
        await roster.getByRole("button", { name: /^(?!Maya Cooper|Leo Cooper).+, not checked in/ }).first().click();
        await mat.waitForTimeout(250);
      }
      await expect(roster.getByRole("button", { name: /, present$/ })).toHaveCount(5);
      await roster.getByRole("button", { name: "Details for Leo Cooper" }).click();
      await mat.getByRole("button", { name: "Award stripe" }).click();
      await expect(mat.getByText(/Stripe awarded/)).toBeVisible();
      const signOff = mat.getByRole("button", { name: /^Sign off / }).first();
      const skill = ((await signOff.getAttribute("aria-label")) ?? "").replace("Sign off ", "");
      await signOff.click();
      await expect(mat.getByText(`✓ ${skill}`).first()).toBeVisible();
      await shot(mat, "04", "mat", `Mat: 5 checked in, a stripe and "${skill}" signed off for Leo`);
      await mat.keyboard.press("Escape");
    });

    await test.step("5. Kiosk: Maya → PIN → check-in → on the Mat roster", async () => {
      const kiosk = await (await ctxFor(browser, "owner", { width: 1024, height: 768 })).newPage();
      await kiosk.goto("/kiosk");
      await kiosk.getByLabel("Device name").fill("Front desk tablet (demo)");
      await kiosk.getByRole("button", { name: "Pair this device" }).click();
      await kiosk.getByRole("textbox", { name: "Name", exact: true }).fill("maya");
      await kiosk.getByRole("list", { name: "Matching students" }).getByRole("button", { name: /Maya Cooper/ }).click();
      await kiosk.getByRole("button", { name: "Continue" }).click();
      for (const d of "4321") await kiosk.getByRole("group", { name: "Family PIN" }).getByRole("button", { name: d, exact: true }).click();
      await expect(kiosk.getByRole("group", { name: "Maya Cooper" }).or(kiosk.getByText(/no classes?/i)).first()).toBeVisible();
      const choices = kiosk.getByRole("group", { name: "Maya Cooper" }).getByRole("button");
      if (!(await choices.count())) {
        await shot(kiosk, "05", "kiosk", "Kiosk: Maya has no class today", "SKIP", "The kiosk only offers today's classes and Maya has none on this weekday.");
        return;
      }
      await kiosk.getByRole("button", { name: "Check in" }).click();
      await expect(kiosk.getByRole("status", { name: "Checked in" })).toContainText("Maya Cooper");
      await shot(kiosk, "05", "kiosk", "Kiosk: Maya checks in with the family PIN");
      const [a] = await sql<{ session_id: string }[]>`select session_id from attendance where person_id = ${MAYA} and source = 'kiosk' order by checked_in_at desc limit 1`;
      await mat.goto(`/mat/session/${a?.session_id}`);
      await expect(mat.getByRole("list", { name: "Roster" }).getByRole("button", { name: "Maya Cooper, present" })).toBeVisible();
      await shot(mat, "05b", "mat-kiosk", "…and she's present on the Mat roster");
    });

    await test.step("6. Home (phone): the stripe, progress, and paying an invoice", async () => {
      await home.goto("/home/progress");
      await expect(home.getByRole("region", { name: "Leo Cooper" }).getByLabel(/\d+ stripes?/).first()).toBeVisible();
      await shot(home, "06", "home-progress", "Home: Leo's new stripe and requirements progress");
      await home.goto("/home/billing");
      if (!stripeReady) {
        await expect(home.getByText("Online card payments aren't available yet.", { exact: false }).first()).toBeVisible();
        await shot(home, "06b", "home-billing", "Home: billing — card payment", "HANDOFF", "Paying with 4242 4242 4242 4242 needs Stripe test keys; without them Home says card payments aren't set up (verified by `tests/e2e/m2/stripe.spec.ts` @stripe once keys are added).");
      } else {
        await shot(home, "06b", "home-billing", "Home: billing — pay with a test card");
      }
    });

    await test.step("7. Billing: a past-due invoice in dunning → payment", async () => {
      if (!stripeReady) {
        await desk.goto("/desk");
        await expect(desk.getByText(/Card retries need Stripe/)).toBeVisible();
      }
      await desk.goto("/desk/reports/ar-aging");
      const row = desk.getByRole("row").filter({ hasText: "step 2" }).first();
      await expect(row).toBeVisible();
      await row.getByRole("link").first().click();
      await desk.waitForURL(/\/desk\/billing\/invoices\//);
      await desk.getByRole("button", { name: "Take payment" }).click();
      await desk.getByRole("radio", { name: "Check" }).check();
      await desk.getByRole("button", { name: "Record payment" }).click();
      await expect(desk.getByRole("dialog")).toBeHidden();
      await expect(desk.getByText(/paid/i).first()).toBeVisible();
      await shot(desk, "07", "dunning", "Billing: a dunning (step 2) invoice paid", stripeReady ? "PASS" : "HANDOFF",
        stripeReady ? "" : "The card retry needs Stripe (the Desk says so); the family's check payment is recorded instead, which clears the dunning state.");
    });

    await test.step("8. POS: a uniform in the size on file, cash", async () => {
      const [{ n: before } = { n: 0 }] = await sql<{ n: number }[]>`select coalesce(sum(l.on_hand), 0)::int as n from inventory_levels l join product_variants v on v.id = l.variant_id where v.tenant_id = ${R} and v.sku = 'DOBOK-1'`;
      await desk.goto("/desk/pos");
      if (await desk.getByRole("button", { name: "Open drawer" }).count()) {
        await desk.getByRole("button", { name: "Open drawer" }).click();
        await desk.getByLabel("Starting cash").fill("100");
        await desk.getByRole("dialog").getByRole("button", { name: "Open drawer" }).click();
      }
      await desk.getByPlaceholder("Attach a household (optional)").fill("Cooper");
      await desk.getByRole("list", { name: "Households" }).getByRole("button", { name: /Cooper/ }).first().click();
      await desk.getByRole("button", { name: "Add dobok (1) for Maya" }).click();
      await expect(desk.getByRole("list", { name: "Cart" }).getByRole("listitem")).toHaveCount(1);
      await desk.getByRole("button", { name: /^Charge \$/ }).click();
      await desk.getByLabel("Cash received").fill("100");
      await desk.getByRole("button", { name: "Take payment" }).click();
      const done = desk.getByRole("status").filter({ hasText: "Sale complete" });
      await expect(done).toBeVisible();
      await done.getByRole("link", { name: "Receipt" }).click();
      await expect(desk.getByRole("article", { name: "Receipt" })).toContainText("Dobok");
      const [{ n: after } = { n: 0 }] = await sql<{ n: number }[]>`select coalesce(sum(l.on_hand), 0)::int as n from inventory_levels l join product_variants v on v.id = l.variant_id where v.tenant_id = ${R} and v.sku = 'DOBOK-1'`;
      expect(after).toBe(before - 1);
      await shot(desk, "08", "pos", "POS: Maya's size (1) from her record, cash, receipt; stock down by one");
    });

    await test.step("9. Testing: auto-roster → invite → Home registers and pays → confirmed", async () => {
      await desk.goto("/desk/testing");
      await desk.getByRole("link", { name: "Saturday Belt Test" }).click();
      await expect(desk.getByRole("heading", { name: /^Eligible/ })).toBeVisible();
      await expect(desk.getByRole("heading", { name: /^Almost/ })).toBeVisible();
      await shot(desk, "09", "testing-roster", "Testing: the auto-roster — eligible and almost (with the named gaps)");
      const notYet = desk.getByRole("button", { name: /not yet eligible/ });
      if (await notYet.count()) await notYet.click();
      const boxes = await desk.getByRole("checkbox", { name: /^Invite / }).all();
      let invitee = "";
      for (const who of ["Leo Cooper", "Maya Cooper"]) if (!invitee && (await desk.getByRole("checkbox", { name: `Invite ${who}` }).count())) invitee = who;
      expect(invitee, "a Cooper child to invite").not.toBe("");
      for (const box of boxes) { if ((await box.getAttribute("aria-label")) === `Invite ${invitee}`) await box.check(); else await box.uncheck(); }
      const reason = desk.getByLabel(/Reason for inviting/);
      if (await reason.count()) await reason.fill("Instructor confident");
      await desk.getByRole("button", { name: "Invite 1 selected" }).click();
      await expect(desk.getByRole("list", { name: "Registrations" }).getByRole("listitem", { name: invitee })).toContainText("invited");
      await home.goto("/home");
      const first = invitee.split(" ")[0] ?? "";
      await home.getByRole("link", { name: new RegExp(`${first} is invited to test`) }).click();
      await home.getByRole("button", { name: `Register ${first}` }).click();
      await expect(home.getByText(/Pay the \$[\d.]+ testing fee/)).toBeVisible();
      await shot(home, "09b", "testing-home", `Home: ${first} registers for the test`);
      const [reg] = await sql<{ invoice_id: string }[]>`select r.invoice_id from testing_registrations r join testing_events t on t.id = r.testing_event_id join people p on p.id = r.person_id
        where t.tenant_id = ${R} and t.name = 'Saturday Belt Test' and p.first_name = ${first} and p.last_name = 'Cooper'`;
      await desk.goto(`/desk/billing/invoices/${reg?.invoice_id}`);
      await desk.getByRole("button", { name: "Take payment" }).click();
      await desk.getByRole("radio", { name: "Cash" }).check();
      await desk.getByRole("button", { name: "Record payment" }).click();
      await expect(desk.getByRole("dialog")).toBeHidden();
      await desk.goto("/desk/testing");
      await desk.getByRole("link", { name: "Saturday Belt Test" }).click();
      await expect(desk.getByRole("list", { name: "Registrations" }).getByRole("listitem", { name: invitee })).toContainText("paid");
      await shot(desk, "09c", "testing-paid", `Testing: ${invitee} registered and paid (fee taken at the desk)`, stripeReady ? "PASS" : "HANDOFF",
        stripeReady ? "" : "Paying the fee by card from Home needs Stripe; the fee was taken in cash at the desk instead.");
    });

    await test.step("10. CRM: lead → Trial scheduled (booking) → Convert → member", async () => {
      await desk.goto("/desk/crm");
      const newCol = desk.getByRole("list", { name: "New leads" });
      const card = newCol.getByRole("listitem").first();
      const leadName = (await card.getAttribute("aria-label")) ?? "";
      const handle = card.getByRole("button", { name: `Drag ${leadName}` });
      const target = desk.getByRole("list", { name: "Trial scheduled leads" });
      const from = await handle.boundingBox();
      const to = await target.boundingBox();
      if (!from || !to) throw new Error("board not laid out");
      await desk.mouse.move(from.x + from.width / 2, from.y + from.height / 2);
      await desk.mouse.down();
      await desk.mouse.move(from.x + 40, from.y + 10, { steps: 5 });
      await desk.mouse.move(to.x + to.width / 2, to.y + 40, { steps: 15 });
      await desk.mouse.up();
      const dialog = desk.getByRole("dialog");
      await dialog.getByLabel("Class").selectOption({ index: 1 });
      await dialog.getByRole("button", { name: "Book trial" }).click();
      await expect(target.getByRole("listitem", { name: leadName })).toBeVisible();
      await shot(desk, "10", "crm-trial", `CRM: ${leadName} dragged to Trial scheduled — a real booking`);
      await desk.getByRole("link", { name: leadName }).click();
      await desk.getByRole("button", { name: "Convert to member" }).click();
      await expect(desk.getByRole("heading", { level: 1, name: "Enroll in membership" })).toBeVisible();
      await desk.getByRole("radio", { name: /Twice Weekly/ }).check();
      await desk.getByRole("button", { name: "Next", exact: true }).click();
      // Twice Weekly includes an enrollment kit: choose sizes once the quote has loaded them.
      await desk.getByLabel("Dobok (uniform)").selectOption({ index: 1 });
      await desk.getByLabel("White belt").selectOption({ index: 1 });
      await desk.getByRole("button", { name: "Next", exact: true }).click();
      await desk.getByRole("radio", { name: "Cash" }).check();
      await desk.getByRole("button", { name: /^Enroll and take/ }).click();
      await expect(desk).toHaveURL(/tab=billing/);
      await expect(desk.getByRole("list", { name: "Memberships" })).toContainText("active");
      await shot(desk, "10b", "crm-member", `CRM: converted — ${leadName} is a member`);
    });

    // ---------------------------------------------------------------- Part 2: what the others can't
    await test.step("11. Copilot: past due + absent 3 weeks → draft SMS → Approvals → approve", async () => {
      await desk.goto("/desk");
      await desk.getByRole("button", { name: "Search (Ctrl+K)" }).click();
      await desk.getByRole("dialog").getByRole("combobox").fill("Which families are past due and haven't attended in 3 weeks?");
      await desk.getByRole("option", { name: /Ask Copilot/ }).click();
      await desk.waitForURL(/\/desk\/copilot/);
      const answer = desk.getByRole("list", { name: "Conversation" }).getByLabel("Copilot answer").last();
      await expect(answer).toContainText("families have an overdue balance", { timeout: 30_000 });
      await expect(answer.getByRole("link", { name: /AR aging/ })).toBeVisible();
      await shot(desk, "11", "copilot", "Copilot: past-due families who haven't trained in 3 weeks — from the data, with the source");
      await desk.getByLabel("Ask the copilot").fill("Draft a friendly SMS to them");
      await desk.getByRole("button", { name: "Ask", exact: true }).click();
      await expect(desk.getByLabel("Copilot answer").last()).toContainText("nothing has been sent", { timeout: 30_000 });
      await desk.goto("/desk/inbox/approvals?kind=copilot_write");
      const draft = desk.getByRole("article").first();
      await expect(draft.getByRole("textbox", { name: "Text message" })).toBeVisible();
      await draft.getByRole("button", { name: "Approve and send" }).click();
      await expect(desk.getByText(/Approved — \d+ messages? queued/)).toBeVisible();
      await shot(desk, "11b", "copilot-approved", "Approvals: the drafted text approved and queued to the Outbox", process.env.TWILIO_AUTH_TOKEN ? "PASS" : "HANDOFF",
        process.env.TWILIO_AUTH_TOKEN ? "" : "Without Twilio keys the Outbox holds the SMS as \"no provider\" — real sending is HANDOFF.");
    });

    await test.step("12. Drift Detector: At risk → Riley #1 with reasons → approve outreach", async () => {
      const [{ n: high } = { n: 0 }] = await sql<{ n: number }[]>`select count(*)::int as n from v_risk_latest where tenant_id = ${R} and level = 'high'`;
      await desk.goto("/desk");
      const atRisk = desk.getByRole("link", { name: /^At risk/ });
      await expect(atRisk).toContainText(String(high));
      await atRisk.click();
      const first = desk.getByRole("list", { name: "Students at risk" }).getByRole("listitem").first();
      await expect(first).toContainText("Riley Adams");
      await expect(first).toContainText(/No class in \d+ days/);
      await shot(desk, "12", "drift", `Drift Detector: ${high} at risk, Riley #1 with the reasons`);
      await desk.goto("/desk/inbox/approvals?kind=drift_outreach");
      const riley = desk.getByRole("article").filter({ hasText: "Riley" }).first();
      await riley.getByRole("button", { name: "Approve and send" }).click();
      await expect(desk.getByText(/Approved — \d+ messages? queued/)).toBeVisible();
      await shot(desk, "12b", "drift-approved", "…the drafted check-in for Riley's family approved");
    });

    await test.step("13. Action board: last night's recorded class → 9 / 3 / 1 → approve all", async () => {
      const [rec] = await sql<{ session_id: string }[]>`select session_id from class_recordings where tenant_id = ${R} and status = 'ready' order by created_at desc limit 1`;
      await mat.goto(`/mat/session/${rec?.session_id}/board`);
      await expect(mat.getByText("dev fixture").first()).toBeVisible();
      await shot(mat, "13", "board", "Action board from last night's recording: 9 check-ins, 3 sign-offs, 1 injury (dev fixture)");
      await mat.getByRole("button", { name: /^Approve/ }).first().click();
      await expect(mat.getByText(/9 check-ins, 3 sign-offs/)).toBeVisible({ timeout: 30_000 });
      await shot(mat, "13b", "board-approved", "…approved: attendance, sign-offs, the injury note and a follow-up task written");
    });

    await test.step("14. Natural-language report → chart → save", async () => {
      await desk.goto("/desk/reports");
      await desk.getByRole("link", { name: "Ask a report" }).click();
      await desk.waitForLoadState("networkidle");
      await desk.getByRole("button", { name: "attendance by program, last 8 weeks" }).click();
      const result = desk.getByRole("region", { name: "Attendance by program — last 8 weeks" });
      await expect(result).toBeVisible({ timeout: 30_000 });
      await expect(result.getByRole("figure").locator("svg .recharts-line").first()).toBeVisible();
      await result.getByLabel("Report name").fill("Program attendance (8 weeks)");
      await result.getByRole("button", { name: "Save as report" }).click();
      await desk.waitForURL(/\/desk\/reports\/saved\//);
      await shot(desk, "14", "nl-report", "Reports → Ask: attendance by program, last 8 weeks — saved");
    });

    await test.step("15. Home: This week + released technique feedback", async () => {
      await home.goto("/home");
      await expect(home.getByRole("region", { name: "This week for Maya Cooper" })).toBeVisible();
      await expect(home.getByRole("region", { name: "This week for Leo Cooper" })).toBeVisible();
      await shot(home, "15", "home-this-week", "Home: this week's staff-approved updates for each child");
      const [sub] = await sql<{ skill_id: string }[]>`select skill_id from technique_submissions where person_id = ${MAYA} and status = 'released' limit 1`;
      await home.goto(`/home/progress/${sub?.skill_id}/submit?student=${MAYA}`);
      const released = home.getByRole("list", { name: "Your clips" }).getByRole("listitem").first();
      await expect(released).toContainText("Feedback ready");
      await expect(released.getByRole("list", { name: "Tips" }).getByRole("listitem")).toHaveCount(3);
      await shot(home, "15b", "technique", "Home: Maya's practice clip with instructor-released feedback (dev fixture)");
    });

    await test.step("Close: Settings → Data export → download the ZIP", async () => {
      await desk.goto("/desk/settings/export");
      await desk.getByRole("button", { name: "Export all data" }).click();
      await expect(desk.getByText(/Export started|Your export is ready/)).toBeVisible();
      await job("data_export");
      await desk.reload();
      const button = desk.getByRole("button", { name: "Download ZIP" }).first();
      await expect(button).toBeVisible({ timeout: 30_000 });
      // The button opens a short-lived signed storage URL in a new tab; catch that request and check it's a ZIP.
      const signed = desk.context().waitForEvent("request", (r) => r.url().includes("/storage/v1/object/sign/"));
      await button.click();
      const url = (await signed).url();
      const zip = await request.get(url);
      expect(zip.ok()).toBe(true);
      expect((await zip.body()).subarray(0, 2).toString()).toBe("PK");
      await shot(desk, "16", "export", "Settings → Data export: the whole school as a ZIP. \"You can leave any time.\"");
    });
  });
});
